#!/bin/bash
#this is for local docker builds, use /host for production
#export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

echo "network configuration"
ifconfig

echo "run the app"
./wifi-connect --portal-interface=wlp4s0

echo "kcf-wifi-connect exited"
while true; do
    sleep 100
done

